export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CARS_SUCCESS = 'LOAD_CARS_SUCCESS';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';

